#!/usr/bin/env python
#  -*- mode:python -*-
"""
  Simple GUI for converting FDF images to DICOM
  and sending them to DaRIS

 - Michael Eager (michael.eager@monash.edu)
 - Monash Biomedical Imaging 
 - (C) 2014 Michael Eager

"""

import os,sys,re

from Tkinter import *
#from Tkinter 
import tkFileDialog

from ReadProcpar import *

aboutText = """<p>Sorry, there is no information about this program. It is
running <b>Agilent2Dicom</b>.
See <a href="http://bitbucket.org/mbi-image/agilent2dicom">Agilent2Dicom Wiki</a></p>"""



def check_dir(dpath):
    if os.path.isdir(dpath) and os.path.exists(os.path.join(dpath,'0001.dcm')):
        return True
    else:
        return False


def senddaris(*args):
    try:
        daris_ID = darisid.get()
        dicom_dir = outputdir.get()
        thispath = os.path.dirname(os.path.realpath(os.path.abspath(__file__)))
        cmd = os.path.join(thispath,'dpush') + ' -c ' + daris_ID + ' -s mf-erc ' + dicom_dir
        os.system(cmd)
    except ValueError:
        pass

def check(*args):  #send_button):
    try:
        import os
        output_dir = outputdir.get()
        thispath = os.path.dirname(os.path.realpath(os.path.abspath(__file__)))
        print 'check path: %s' % thispath
        cmd1 = os.path.join(thispath,'dcheck.sh') + ' -o ' + output_dir
        print(cmd1)
        cmd='(if test ${MASSIVEUSERNAME+defined} \n\
then \n\
  echo ''On Massive'' \n\
  module unload python/3.3.5-gcc \n\
  module load python \n\
fi \n\
echo ''Done''\n ' + cmd1 +')'
        print(cmd)
        os.system(cmd)
        if check_dir(output_dir):
            print 'Ready to send dicoms to DaRIS'
 #           send_button.foreground="dark green"
 #           send_button.state='active'
    except ValueError:
        pass


def convert(*args):  #send_button):
    try:
        import os
        input_dir = inputdir.get()
        output_dir = outputdir.get()
        thispath = os.path.dirname(os.path.realpath(os.path.abspath(__file__)))
        print 'dconvert path: %s' % thispath
        cmd1 = os.path.join(thispath,'fdf2dcm.sh') + ' -v  -i ' + input_dir + ' -o ' + output_dir
        print(cmd1)
        cmd='(if test ${MASSIVEUSERNAME+defined} \n\
then \n\
  echo ''On Massive'' \n\
  module unload python/3.3.5-gcc \n\
  module load python \n\
fi \n\
echo ''Done''\n ' + cmd1 +')'
        print(cmd)
        os.system(cmd)
        if check_dir(output_dir):
            print 'Ready to send dicoms to DaRIS'
 #           send_button.foreground="dark green"
 #           send_button.state='active'
    except ValueError:
        pass

def GetDarisID(*args):
    daris_id=''
    try:
        procpar, procpartext = ReadProcpar(inputdir.get() + '/procpar')
        if 'name' in procpar.keys():
            if re.search('DaRIS',procpar['name']):
                daris_id = re.sub('DaRIS\^','',procpar['name'])
    except ValueError:
        pass
    return daris_id


def loadinputdir(*args):
    dir_ = tkFileDialog.askdirectory(initialdir=inputdir.get(), title="Choose FDF directory", mustexist=True) # parent,
    if re.search('img',dir_):
        out = re.sub('img','dcm',dir_)
    else:
        out = dir_+'.dcm'
    inputdir.set(dir_)
    outputdir.set(out)
    darisid.set(GetDarisID())

def loadoutputdir(*args):
    dir_ = tkFileDialog.askdirectory(initialdir=outputdir.get(), title="Choose DICOM directory",mustexist=False) # parent,
    outputdir.set(dir_)

def toggle_debug():
    d = debug.get()
    if d == 0:
        debug.set(1)
    else:
        debug.set(0)

def onAbout():
    tkMessageBox.showinfo("FDF2Dicom About", aboutText)

root = Tk()
root.title("FDF to Dicom/3.0 (MBI Agilent)")
thispath = os.path.dirname(os.path.realpath(os.path.abspath(__file__)))
print(thispath)
mainframe = Frame(root)
mainframe.grid(column=0, row=0, sticky=(N, W, E, S))
mainframe.columnconfigure(0, weight=1)
mainframe.rowconfigure(0, weight=1)


menu = Menu(root)
root.config(menu=menu)
filemenu = Menu(menu)
menu.add_cascade(label="Settings", menu=filemenu)

filemenu.add_command(label="Toggle debug", command=toggle_debug)

filemenu.add_command(label="Exit", command=root.quit)
aboutmenu = Menu(menu)
menu.add_cascade(label="Help", menu=aboutmenu)
filemenu.add_command(label="About FDF2Dicom", command=onAbout)



debug = IntVar()
debug.set(0)

inputdir = StringVar()
outputdir = StringVar()
darisid = StringVar()

if re.search('img',os.getcwd()):
    out = re.sub('img','dcm',os.getcwd())
else:
    out = os.getcwd()+'.dcm'

inputdir.set(os.getcwd())
outputdir.set(out)


inputdir_entry = Entry(mainframe, width=25, textvariable=inputdir)
inputdir_entry.grid(column=2, row=1, sticky=(W, E))

outputdir_entry = Entry(mainframe, width=25, textvariable=outputdir)
outputdir_entry.grid(column=2, row=2, sticky=(W, E))

darisid_entry = Entry(mainframe, width=25, textvariable=darisid)
darisid_entry.grid(column=2, row=3, sticky=(W, E))

# Radiobutton(mainframe,text="Debug",variable=debug,padx=10).grid(column=1,row=4,sticky=W)

#Label(mainframe, textvariable=outputdir).grid(column=2, row=2, sticky=(W, E))
Button(mainframe, text="Choose Dir", command=loadinputdir).grid(column=3,row=1,sticky=W)
Button(mainframe, text="Choose Dir", command=loadoutputdir).grid(column=3,row=2,sticky=W)

send_button = Button(mainframe, text="Send", command=senddaris,state='active',foreground="black").grid(column=2, row=4, sticky=E)
#send_button.config()
Button(mainframe, text="Convert", command=convert).grid(column=1, row=4, sticky=E)
Button(mainframe, text="Check", command=check).grid(column=2, row=4, sticky=W)
Button(mainframe,text="Cancel",command=root.destroy).grid(column=3,row=4,sticky=W)


Label(mainframe, text="Input dir (FDF img)").grid(column=1, row=1, sticky=W)
Label(mainframe, text="DCM directory").grid(column=1, row=2, sticky=E)
Label(mainframe, text="DaRIS ID").grid(column=1, row=3, sticky=E)


for child in mainframe.winfo_children(): child.grid_configure(padx=5, pady=5)

inputdir_entry.focus()
root.bind('<Return>', convert)

root.mainloop()
