# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FDF2DicomQt.ui'
#
# Created: Mon Sep 29 19:24:53 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(559, 442)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(200, 400, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 19, 541, 371))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_fdf = QtGui.QWidget()
        self.tab_fdf.setObjectName(_fromUtf8("tab_fdf"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab_fdf)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 511, 321))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_convert = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_convert.setObjectName(_fromUtf8("pushButton_convert"))
        self.gridLayout.addWidget(self.pushButton_convert, 3, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.pushButton_changefdf = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_changefdf.setObjectName(_fromUtf8("pushButton_changefdf"))
        self.gridLayout.addWidget(self.pushButton_changefdf, 0, 4, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.pushButton_send2daris = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_send2daris.setObjectName(_fromUtf8("pushButton_send2daris"))
        self.gridLayout.addWidget(self.pushButton_send2daris, 5, 4, 1, 1)
        self.pushButton_changedicom = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_changedicom.setObjectName(_fromUtf8("pushButton_changedicom"))
        self.gridLayout.addWidget(self.pushButton_changedicom, 1, 4, 1, 1)
        self.lineEdit_darisid = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_darisid.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_darisid.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_darisid.setObjectName(_fromUtf8("lineEdit_darisid"))
        self.gridLayout.addWidget(self.lineEdit_darisid, 2, 3, 1, 1)
        self.lineEdit_fdfpath = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_fdfpath.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_fdfpath.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_fdfpath.setObjectName(_fromUtf8("lineEdit_fdfpath"))
        self.gridLayout.addWidget(self.lineEdit_fdfpath, 0, 3, 1, 1)
        self.lineEdit_dicompath = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_dicompath.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_dicompath.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_dicompath.setObjectName(_fromUtf8("lineEdit_dicompath"))
        self.gridLayout.addWidget(self.lineEdit_dicompath, 1, 3, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_check = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_check.setObjectName(_fromUtf8("pushButton_check"))
        self.horizontalLayout.addWidget(self.pushButton_check)
        self.pushButton_view = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_view.setObjectName(_fromUtf8("pushButton_view"))
        self.horizontalLayout.addWidget(self.pushButton_view)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 3, 1, 1)
        self.Multiecho = QtGui.QTabWidget(self.gridLayoutWidget)
        self.Multiecho.setObjectName(_fromUtf8("Multiecho"))
        self.tab_generic = QtGui.QWidget()
        self.tab_generic.setObjectName(_fromUtf8("tab_generic"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.tab_generic)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(9, 9, 291, 101))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.radioButton_debugging = QtGui.QRadioButton(self.gridLayoutWidget_4)
        self.radioButton_debugging.setObjectName(_fromUtf8("radioButton_debugging"))
        self.gridLayout_5.addWidget(self.radioButton_debugging, 0, 0, 1, 1)
        self.radioButton_nodcmulti = QtGui.QRadioButton(self.gridLayoutWidget_4)
        self.radioButton_nodcmulti.setObjectName(_fromUtf8("radioButton_nodcmulti"))
        self.gridLayout_5.addWidget(self.radioButton_nodcmulti, 1, 0, 1, 1)
        self.Multiecho.addTab(self.tab_generic, _fromUtf8(""))
        self.tab_diffusion = QtGui.QWidget()
        self.tab_diffusion.setObjectName(_fromUtf8("tab_diffusion"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tab_diffusion)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 291, 131))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.radioButton_bmatrixdiff = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_bmatrixdiff.setObjectName(_fromUtf8("radioButton_bmatrixdiff"))
        self.gridLayout_2.addWidget(self.radioButton_bmatrixdiff, 0, 1, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.radioButton_directionaldiff = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_directionaldiff.setObjectName(_fromUtf8("radioButton_directionaldiff"))
        self.horizontalLayout_5.addWidget(self.radioButton_directionaldiff)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 7, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_4.addWidget(self.label_10)
        self.lineEdit_7 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.horizontalLayout_4.addWidget(self.lineEdit_7)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 7, 0, 1, 1)
        self.radioButton_diffusion1 = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_diffusion1.setObjectName(_fromUtf8("radioButton_diffusion1"))
        self.gridLayout_2.addWidget(self.radioButton_diffusion1, 0, 0, 1, 1)
        self.Multiecho.addTab(self.tab_diffusion, _fromUtf8(""))
        self.tab_multiecho = QtGui.QWidget()
        self.tab_multiecho.setObjectName(_fromUtf8("tab_multiecho"))
        self.gridLayoutWidget_5 = QtGui.QWidget(self.tab_multiecho)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 10, 291, 61))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(5)
        self.horizontalLayout_10.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.gridLayout_6.addLayout(self.horizontalLayout_10, 6, 0, 1, 1)
        self.radioButton_7 = QtGui.QRadioButton(self.gridLayoutWidget_5)
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.gridLayout_6.addWidget(self.radioButton_7, 0, 1, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(5)
        self.horizontalLayout_11.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_11.addWidget(self.label_15)
        self.lineEdit_12 = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.horizontalLayout_11.addWidget(self.lineEdit_12)
        self.gridLayout_6.addLayout(self.horizontalLayout_11, 6, 1, 1, 1)
        self.Multiecho.addTab(self.tab_multiecho, _fromUtf8(""))
        self.gridLayout.addWidget(self.Multiecho, 3, 3, 1, 1)
        self.tabWidget.addTab(self.tab_fdf, _fromUtf8(""))
        self.tab_fid = QtGui.QWidget()
        self.tab_fid.setObjectName(_fromUtf8("tab_fid"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tab_fid)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 511, 321))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButton_convertfid = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_convertfid.setObjectName(_fromUtf8("pushButton_convertfid"))
        self.gridLayout_3.addWidget(self.pushButton_convertfid, 3, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 3, 1, 1, 1)
        self.pushButton_changefid = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_changefid.setObjectName(_fromUtf8("pushButton_changefid"))
        self.gridLayout_3.addWidget(self.pushButton_changefid, 0, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 2, 1, 1, 1)
        self.pushButton_changedicom2 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_changedicom2.setObjectName(_fromUtf8("pushButton_changedicom2"))
        self.gridLayout_3.addWidget(self.pushButton_changedicom2, 1, 3, 1, 1)
        self.lineEdit_darisid2 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_darisid2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_darisid2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_darisid2.setObjectName(_fromUtf8("lineEdit_darisid2"))
        self.gridLayout_3.addWidget(self.lineEdit_darisid2, 2, 2, 1, 1)
        self.lineEdit_fidpath = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_fidpath.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_fidpath.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_fidpath.setObjectName(_fromUtf8("lineEdit_fidpath"))
        self.gridLayout_3.addWidget(self.lineEdit_fidpath, 0, 2, 1, 1)
        self.lineEdit_dicompath2 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_dicompath2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_dicompath2.setText(_fromUtf8(""))
        self.lineEdit_dicompath2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_dicompath2.setObjectName(_fromUtf8("lineEdit_dicompath2"))
        self.gridLayout_3.addWidget(self.lineEdit_dicompath2, 1, 2, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.radioButton = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.gridLayout_4.addWidget(self.radioButton, 0, 1, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.gridLayout_4.addWidget(self.radioButton_2, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 2, 1, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_6.addWidget(self.label_12)
        self.lineEdit_window = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_window.setObjectName(_fromUtf8("lineEdit_window"))
        self.horizontalLayout_6.addWidget(self.lineEdit_window)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_8.addWidget(self.label_14)
        self.lineEdit_sigma = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_sigma.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_sigma.setObjectName(_fromUtf8("lineEdit_sigma"))
        self.horizontalLayout_8.addWidget(self.lineEdit_sigma)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.radioButton_9 = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_9.setObjectName(_fromUtf8("radioButton_9"))
        self.horizontalLayout_9.addWidget(self.radioButton_9)
        self.gridLayout_4.addLayout(self.horizontalLayout_9, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 3, 2, 1, 1)
        self.pushButton_send2daris2 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_send2daris2.setObjectName(_fromUtf8("pushButton_send2daris2"))
        self.gridLayout_3.addWidget(self.pushButton_send2daris2, 4, 3, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_check2 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_check2.setObjectName(_fromUtf8("pushButton_check2"))
        self.horizontalLayout_2.addWidget(self.pushButton_check2)
        self.pushButton_view2 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_view2.setObjectName(_fromUtf8("pushButton_view2"))
        self.horizontalLayout_2.addWidget(self.pushButton_view2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 4, 2, 1, 1)
        self.tabWidget.addTab(self.tab_fid, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.Multiecho.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit_fdfpath, self.pushButton_changefdf)
        Dialog.setTabOrder(self.pushButton_changefdf, self.lineEdit_dicompath)
        Dialog.setTabOrder(self.lineEdit_dicompath, self.pushButton_changedicom)
        Dialog.setTabOrder(self.pushButton_changedicom, self.lineEdit_darisid)
        Dialog.setTabOrder(self.lineEdit_darisid, self.pushButton_convert)
        Dialog.setTabOrder(self.pushButton_convert, self.pushButton_check)
        Dialog.setTabOrder(self.pushButton_check, self.pushButton_view)
        Dialog.setTabOrder(self.pushButton_view, self.pushButton_send2daris)
        Dialog.setTabOrder(self.pushButton_send2daris, self.buttonBox)
        Dialog.setTabOrder(self.buttonBox, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.lineEdit_fidpath)
        Dialog.setTabOrder(self.lineEdit_fidpath, self.pushButton_changefid)
        Dialog.setTabOrder(self.pushButton_changefid, self.lineEdit_dicompath2)
        Dialog.setTabOrder(self.lineEdit_dicompath2, self.pushButton_changedicom2)
        Dialog.setTabOrder(self.pushButton_changedicom2, self.lineEdit_darisid2)
        Dialog.setTabOrder(self.lineEdit_darisid2, self.pushButton_convertfid)
        Dialog.setTabOrder(self.pushButton_convertfid, self.pushButton_check2)
        Dialog.setTabOrder(self.pushButton_check2, self.pushButton_send2daris2)
        Dialog.setTabOrder(self.pushButton_send2daris2, self.radioButton_2)
        Dialog.setTabOrder(self.radioButton_2, self.radioButton)
        Dialog.setTabOrder(self.radioButton, self.lineEdit_sigma)
        Dialog.setTabOrder(self.lineEdit_sigma, self.lineEdit_window)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.pushButton_convert.setText(_translate("Dialog", "Convert", None))
        self.label_4.setText(_translate("Dialog", "Options", None))
        self.pushButton_changefdf.setToolTip(_translate("Dialog", "Change the FDF input directory", None))
        self.pushButton_changefdf.setText(_translate("Dialog", "Change Dir", None))
        self.label.setText(_translate("Dialog", "FDF folder", None))
        self.label_2.setText(_translate("Dialog", "Dicom folder", None))
        self.label_3.setText(_translate("Dialog", "DaRIS ID", None))
        self.pushButton_send2daris.setText(_translate("Dialog", "Send to DaRIS", None))
        self.pushButton_changedicom.setToolTip(_translate("Dialog", "Change the output DICOM directory.  Only do this if the automatic folder name is already taken.", None))
        self.pushButton_changedicom.setText(_translate("Dialog", "Change Dir", None))
        self.pushButton_check.setText(_translate("Dialog", "Check", None))
        self.pushButton_view.setText(_translate("Dialog", "View", None))
        self.radioButton_debugging.setToolTip(_translate("Dialog", "Display more verbose debugging", None))
        self.radioButton_debugging.setText(_translate("Dialog", "Show debugging", None))
        self.radioButton_nodcmulti.setToolTip(_translate("Dialog", "Do not convert 2D slices to enhance DICOM format", None))
        self.radioButton_nodcmulti.setText(_translate("Dialog", "Keep 2D DICOM slices", None))
        self.Multiecho.setTabText(self.Multiecho.indexOf(self.tab_generic), _translate("Dialog", "Generic", None))
        self.radioButton_bmatrixdiff.setText(_translate("Dialog", "Bmatrix", None))
        self.radioButton_directionaldiff.setText(_translate("Dialog", "Directional", None))
        self.label_10.setText(_translate("Dialog", "TextLabel", None))
        self.radioButton_diffusion1.setText(_translate("Dialog", "Diffusion", None))
        self.Multiecho.setTabText(self.Multiecho.indexOf(self.tab_diffusion), _translate("Dialog", "Diffusion", None))
        self.radioButton_7.setText(_translate("Dialog", "Multi-echo", None))
        self.label_15.setText(_translate("Dialog", "TextLabel", None))
        self.Multiecho.setTabText(self.Multiecho.indexOf(self.tab_multiecho), _translate("Dialog", "Multi echo", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_fdf), _translate("Dialog", "FDF converter", None))
        self.pushButton_convertfid.setText(_translate("Dialog", "Convert", None))
        self.label_5.setText(_translate("Dialog", "Options", None))
        self.pushButton_changefid.setToolTip(_translate("Dialog", "Change the input FID directory", None))
        self.pushButton_changefid.setText(_translate("Dialog", "Change Dir", None))
        self.label_6.setText(_translate("Dialog", "FID folder", None))
        self.label_7.setText(_translate("Dialog", "Dicom folder", None))
        self.label_8.setText(_translate("Dialog", "DaRIS ID", None))
        self.pushButton_changedicom2.setToolTip(_translate("Dialog", "Change the output DICOM directory.", None))
        self.pushButton_changedicom2.setText(_translate("Dialog", "Change Dir", None))
        self.lineEdit_darisid2.setToolTip(_translate("Dialog", "DaRIS ID generated from header information in FID procpar.  Do not edit unless you know what you are doing!", None))
        self.radioButton.setText(_translate("Dialog", "Save K-space", None))
        self.radioButton_2.setText(_translate("Dialog", "Use Gaussian Filter", None))
        self.label_12.setText(_translate("Dialog", "Window Size", None))
        self.lineEdit_window.setText(_translate("Dialog", "5", None))
        self.label_14.setText(_translate("Dialog", "Sigma", None))
        self.lineEdit_sigma.setText(_translate("Dialog", "0.707", None))
        self.radioButton_9.setText(_translate("Dialog", "Isotropic", None))
        self.pushButton_send2daris2.setText(_translate("Dialog", "Send to DaRIS", None))
        self.pushButton_check2.setText(_translate("Dialog", "Check", None))
        self.pushButton_view2.setText(_translate("Dialog", "View", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_fid), _translate("Dialog", "FID converter", None))

