# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FDF2DicomQt.ui'
#
# Created: Thu Sep 25 13:10:14 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(563, 444)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(200, 400, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 19, 541, 371))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 511, 321))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_3 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout.addWidget(self.pushButton_3, 3, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 0, 4, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout.addWidget(self.pushButton_4, 5, 4, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 1, 4, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 2, 3, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 0, 3, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout.addWidget(self.lineEdit_3, 1, 3, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_4.addWidget(self.label_10)
        self.lineEdit_7 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.horizontalLayout_4.addWidget(self.lineEdit_7)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 6, 0, 1, 1)
        self.radioButton_3 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.gridLayout_2.addWidget(self.radioButton_3, 0, 1, 1, 1)
        self.radioButton_4 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.gridLayout_2.addWidget(self.radioButton_4, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_5.addWidget(self.label_11)
        self.lineEdit_8 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.horizontalLayout_5.addWidget(self.lineEdit_8)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 6, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 3, 3, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_6 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.pushButton_5 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout.addWidget(self.pushButton_5)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 3, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 511, 321))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButton_7 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_3.addWidget(self.pushButton_7, 3, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 3, 1, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_3.addWidget(self.pushButton_8, 0, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 2, 1, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_3.addWidget(self.pushButton_9, 1, 3, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout_3.addWidget(self.lineEdit_4, 2, 2, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout_3.addWidget(self.lineEdit_5, 0, 2, 1, 1)
        self.lineEdit_6 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout_3.addWidget(self.lineEdit_6, 1, 2, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.radioButton = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.gridLayout_4.addWidget(self.radioButton, 0, 1, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.gridLayout_4.addWidget(self.radioButton_2, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_7.addWidget(self.label_13)
        self.lineEdit_10 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.horizontalLayout_7.addWidget(self.lineEdit_10)
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 2, 1, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_6.addWidget(self.label_12)
        self.lineEdit_9 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.horizontalLayout_6.addWidget(self.lineEdit_9)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_8.addWidget(self.label_14)
        self.lineEdit_11 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.horizontalLayout_8.addWidget(self.lineEdit_11)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_9.addWidget(self.label_15)
        self.lineEdit_12 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.horizontalLayout_9.addWidget(self.lineEdit_12)
        self.gridLayout_4.addLayout(self.horizontalLayout_9, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 3, 2, 1, 1)
        self.pushButton_10 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout_3.addWidget(self.pushButton_10, 4, 3, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_11 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.horizontalLayout_2.addWidget(self.pushButton_11)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_12 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.horizontalLayout_2.addWidget(self.pushButton_12)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 4, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit_2, self.pushButton)
        Dialog.setTabOrder(self.pushButton, self.lineEdit_3)
        Dialog.setTabOrder(self.lineEdit_3, self.pushButton_2)
        Dialog.setTabOrder(self.pushButton_2, self.lineEdit)
        Dialog.setTabOrder(self.lineEdit, self.pushButton_3)
        Dialog.setTabOrder(self.pushButton_3, self.pushButton_6)
        Dialog.setTabOrder(self.pushButton_6, self.pushButton_5)
        Dialog.setTabOrder(self.pushButton_5, self.pushButton_4)
        Dialog.setTabOrder(self.pushButton_4, self.buttonBox)
        Dialog.setTabOrder(self.buttonBox, self.radioButton_4)
        Dialog.setTabOrder(self.radioButton_4, self.radioButton_3)
        Dialog.setTabOrder(self.radioButton_3, self.lineEdit_7)
        Dialog.setTabOrder(self.lineEdit_7, self.lineEdit_8)
        Dialog.setTabOrder(self.lineEdit_8, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.lineEdit_5)
        Dialog.setTabOrder(self.lineEdit_5, self.pushButton_8)
        Dialog.setTabOrder(self.pushButton_8, self.lineEdit_6)
        Dialog.setTabOrder(self.lineEdit_6, self.pushButton_9)
        Dialog.setTabOrder(self.pushButton_9, self.lineEdit_4)
        Dialog.setTabOrder(self.lineEdit_4, self.pushButton_7)
        Dialog.setTabOrder(self.pushButton_7, self.pushButton_11)
        Dialog.setTabOrder(self.pushButton_11, self.pushButton_12)
        Dialog.setTabOrder(self.pushButton_12, self.pushButton_10)
        Dialog.setTabOrder(self.pushButton_10, self.radioButton_2)
        Dialog.setTabOrder(self.radioButton_2, self.radioButton)
        Dialog.setTabOrder(self.radioButton, self.lineEdit_11)
        Dialog.setTabOrder(self.lineEdit_11, self.lineEdit_9)
        Dialog.setTabOrder(self.lineEdit_9, self.lineEdit_12)
        Dialog.setTabOrder(self.lineEdit_12, self.lineEdit_10)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.pushButton_3.setText(_translate("Dialog", "Convert", None))
        self.label_4.setText(_translate("Dialog", "Options", None))
        self.pushButton.setText(_translate("Dialog", "Change Dir", None))
        self.label.setText(_translate("Dialog", "FDF folder", None))
        self.label_2.setText(_translate("Dialog", "Dicom folder", None))
        self.label_3.setText(_translate("Dialog", "DaRIS ID", None))
        self.pushButton_4.setText(_translate("Dialog", "Send to DaRIS", None))
        self.pushButton_2.setText(_translate("Dialog", "Change Dir", None))
        self.label_10.setText(_translate("Dialog", "TextLabel", None))
        self.radioButton_3.setText(_translate("Dialog", "Multi-echo", None))
        self.radioButton_4.setText(_translate("Dialog", "Diffusion", None))
        self.label_11.setText(_translate("Dialog", "TextLabel", None))
        self.pushButton_6.setText(_translate("Dialog", "Check", None))
        self.pushButton_5.setText(_translate("Dialog", "View", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "FDF converter", None))
        self.pushButton_7.setText(_translate("Dialog", "Convert", None))
        self.label_5.setText(_translate("Dialog", "Options", None))
        self.pushButton_8.setText(_translate("Dialog", "Change Dir", None))
        self.label_6.setText(_translate("Dialog", "FID folder", None))
        self.label_7.setText(_translate("Dialog", "Dicom folder", None))
        self.label_8.setText(_translate("Dialog", "DaRIS ID", None))
        self.pushButton_9.setText(_translate("Dialog", "Change Dir", None))
        self.radioButton.setText(_translate("Dialog", "Median Filter", None))
        self.radioButton_2.setText(_translate("Dialog", "Gaussian Filter", None))
        self.label_13.setText(_translate("Dialog", "TextLabel", None))
        self.label_12.setText(_translate("Dialog", "Window Size", None))
        self.label_14.setText(_translate("Dialog", "Sigma", None))
        self.label_15.setText(_translate("Dialog", "Window Size", None))
        self.pushButton_10.setText(_translate("Dialog", "Send to DaRIS", None))
        self.pushButton_11.setText(_translate("Dialog", "Check", None))
        self.pushButton_12.setText(_translate("Dialog", "View", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "FID converter", None))

