# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FDF2DicomQt.ui'
#
# Created: Fri Oct  3 08:37:26 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(558, 441)
        Dialog.setToolTip(_fromUtf8(""))
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(200, 400, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 19, 541, 371))
        self.tabWidget.setToolTip(_fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_fdf = QtGui.QWidget()
        self.tab_fdf.setObjectName(_fromUtf8("tab_fdf"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab_fdf)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 511, 321))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.pushButton_changefdf = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_changefdf.setObjectName(_fromUtf8("pushButton_changefdf"))
        self.gridLayout.addWidget(self.pushButton_changefdf, 0, 4, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.pushButton_changedicom = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_changedicom.setObjectName(_fromUtf8("pushButton_changedicom"))
        self.gridLayout.addWidget(self.pushButton_changedicom, 1, 4, 1, 1)
        self.lineEdit_darisid = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_darisid.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_darisid.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_darisid.setObjectName(_fromUtf8("lineEdit_darisid"))
        self.gridLayout.addWidget(self.lineEdit_darisid, 2, 3, 1, 1)
        self.lineEdit_fdfpath = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_fdfpath.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_fdfpath.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_fdfpath.setObjectName(_fromUtf8("lineEdit_fdfpath"))
        self.gridLayout.addWidget(self.lineEdit_fdfpath, 0, 3, 1, 1)
        self.lineEdit_dicompath = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_dicompath.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_dicompath.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_dicompath.setObjectName(_fromUtf8("lineEdit_dicompath"))
        self.gridLayout.addWidget(self.lineEdit_dicompath, 1, 3, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout.addLayout(self.horizontalLayout, 5, 3, 1, 1)
        self.Multiecho = QtGui.QTabWidget(self.gridLayoutWidget)
        self.Multiecho.setEnabled(False)
        self.Multiecho.setObjectName(_fromUtf8("Multiecho"))
        self.tab_generic = QtGui.QWidget()
        self.tab_generic.setObjectName(_fromUtf8("tab_generic"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.tab_generic)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(9, 9, 291, 101))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.checkBox_debugging = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_debugging.setObjectName(_fromUtf8("checkBox_debugging"))
        self.gridLayout_5.addWidget(self.checkBox_debugging, 0, 0, 1, 1)
        self.checkBox_nodcmulti = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_nodcmulti.setObjectName(_fromUtf8("checkBox_nodcmulti"))
        self.gridLayout_5.addWidget(self.checkBox_nodcmulti, 1, 0, 1, 1)
        self.Multiecho.addTab(self.tab_generic, _fromUtf8(""))
        self.tab_diffusion = QtGui.QWidget()
        self.tab_diffusion.setEnabled(False)
        self.tab_diffusion.setObjectName(_fromUtf8("tab_diffusion"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tab_diffusion)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 291, 131))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.radioButton_bmatrixdiff = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_bmatrixdiff.setObjectName(_fromUtf8("radioButton_bmatrixdiff"))
        self.horizontalLayout_5.addWidget(self.radioButton_bmatrixdiff)
        self.radioButton_directionaldiff = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_directionaldiff.setObjectName(_fromUtf8("radioButton_directionaldiff"))
        self.horizontalLayout_5.addWidget(self.radioButton_directionaldiff)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 7, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_4.addWidget(self.label_10)
        self.lineEdit_7 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.horizontalLayout_4.addWidget(self.lineEdit_7)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 7, 0, 1, 1)
        self.checkBox_diffusion1 = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_diffusion1.setObjectName(_fromUtf8("checkBox_diffusion1"))
        self.gridLayout_2.addWidget(self.checkBox_diffusion1, 0, 0, 1, 1)
        self.Multiecho.addTab(self.tab_diffusion, _fromUtf8(""))
        self.tab_multiecho = QtGui.QWidget()
        self.tab_multiecho.setEnabled(False)
        self.tab_multiecho.setObjectName(_fromUtf8("tab_multiecho"))
        self.gridLayoutWidget_5 = QtGui.QWidget(self.tab_multiecho)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 10, 291, 61))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(5)
        self.horizontalLayout_10.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.gridLayout_6.addLayout(self.horizontalLayout_10, 6, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(5)
        self.horizontalLayout_11.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_11.addWidget(self.label_15)
        self.lineEdit_12 = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.horizontalLayout_11.addWidget(self.lineEdit_12)
        self.gridLayout_6.addLayout(self.horizontalLayout_11, 6, 1, 1, 1)
        self.checkBox_7 = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.gridLayout_6.addWidget(self.checkBox_7, 0, 1, 1, 1)
        self.Multiecho.addTab(self.tab_multiecho, _fromUtf8(""))
        self.gridLayout.addWidget(self.Multiecho, 3, 3, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_convert = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_convert.setObjectName(_fromUtf8("pushButton_convert"))
        self.verticalLayout.addWidget(self.pushButton_convert)
        self.pushButton_check = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_check.setEnabled(False)
        self.pushButton_check.setObjectName(_fromUtf8("pushButton_check"))
        self.verticalLayout.addWidget(self.pushButton_check)
        self.pushButton_view = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_view.setEnabled(False)
        self.pushButton_view.setObjectName(_fromUtf8("pushButton_view"))
        self.verticalLayout.addWidget(self.pushButton_view)
        self.pushButton_send2daris = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_send2daris.setEnabled(False)
        self.pushButton_send2daris.setObjectName(_fromUtf8("pushButton_send2daris"))
        self.verticalLayout.addWidget(self.pushButton_send2daris)
        self.gridLayout.addLayout(self.verticalLayout, 3, 4, 1, 1)
        self.tabWidget.addTab(self.tab_fdf, _fromUtf8(""))
        self.tab_fid = QtGui.QWidget()
        self.tab_fid.setObjectName(_fromUtf8("tab_fid"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tab_fid)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 511, 321))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 3, 1, 1, 1)
        self.pushButton_changefid = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_changefid.setObjectName(_fromUtf8("pushButton_changefid"))
        self.gridLayout_3.addWidget(self.pushButton_changefid, 0, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 1, 1, 1, 1)
        self.pushButton_changedicom2 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_changedicom2.setObjectName(_fromUtf8("pushButton_changedicom2"))
        self.gridLayout_3.addWidget(self.pushButton_changedicom2, 1, 3, 1, 1)
        self.lineEdit_darisid2 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_darisid2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_darisid2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_darisid2.setObjectName(_fromUtf8("lineEdit_darisid2"))
        self.gridLayout_3.addWidget(self.lineEdit_darisid2, 2, 2, 1, 1)
        self.lineEdit_fidpath = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_fidpath.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_fidpath.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_fidpath.setObjectName(_fromUtf8("lineEdit_fidpath"))
        self.gridLayout_3.addWidget(self.lineEdit_fidpath, 0, 2, 1, 1)
        self.lineEdit_dicompath2 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_dicompath2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_dicompath2.setText(_fromUtf8(""))
        self.lineEdit_dicompath2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_dicompath2.setObjectName(_fromUtf8("lineEdit_dicompath2"))
        self.gridLayout_3.addWidget(self.lineEdit_dicompath2, 1, 2, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pushButton_convertfid = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_convertfid.setObjectName(_fromUtf8("pushButton_convertfid"))
        self.verticalLayout_2.addWidget(self.pushButton_convertfid)
        self.pushButton_check2 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_check2.setEnabled(False)
        self.pushButton_check2.setObjectName(_fromUtf8("pushButton_check2"))
        self.verticalLayout_2.addWidget(self.pushButton_check2)
        self.pushButton_view2 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_view2.setEnabled(False)
        self.pushButton_view2.setObjectName(_fromUtf8("pushButton_view2"))
        self.verticalLayout_2.addWidget(self.pushButton_view2)
        self.pushButton_send2daris2 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_send2daris2.setEnabled(False)
        self.pushButton_send2daris2.setObjectName(_fromUtf8("pushButton_send2daris2"))
        self.verticalLayout_2.addWidget(self.pushButton_send2daris2)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 3, 3, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_3.addWidget(self.label_9)
        self.tabWidget_2 = QtGui.QTabWidget(self.gridLayoutWidget_3)
        self.tabWidget_2.setEnabled(True)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.layoutWidget_2 = QtGui.QWidget(self.tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 10, 301, 101))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.gridLayout_9 = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setSpacing(5)
        self.horizontalLayout_25.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.gridLayout_9.addLayout(self.horizontalLayout_25, 1, 1, 1, 1)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setSpacing(5)
        self.horizontalLayout_26.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_19 = QtGui.QLabel(self.layoutWidget_2)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_26.addWidget(self.label_19)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem)
        self.lineEdit_window_4 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit_window_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_window_4.setObjectName(_fromUtf8("lineEdit_window_4"))
        self.horizontalLayout_26.addWidget(self.lineEdit_window_4)
        self.gridLayout_9.addLayout(self.horizontalLayout_26, 2, 0, 1, 1)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setSpacing(5)
        self.horizontalLayout_27.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_20 = QtGui.QLabel(self.layoutWidget_2)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_27.addWidget(self.label_20)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem1)
        self.lineEdit_sigma_4 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit_sigma_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_sigma_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_sigma_4.setObjectName(_fromUtf8("lineEdit_sigma_4"))
        self.horizontalLayout_27.addWidget(self.lineEdit_sigma_4)
        self.gridLayout_9.addLayout(self.horizontalLayout_27, 1, 0, 1, 1)
        self.checkBox_24 = QtGui.QCheckBox(self.layoutWidget_2)
        self.checkBox_24.setObjectName(_fromUtf8("checkBox_24"))
        self.gridLayout_9.addWidget(self.checkBox_24, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.tab_2)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(0, 10, 281, 71))
        self.verticalLayoutWidget_6.setObjectName(_fromUtf8("verticalLayoutWidget_6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.checkBox_36 = QtGui.QCheckBox(self.verticalLayoutWidget_6)
        self.checkBox_36.setObjectName(_fromUtf8("checkBox_36"))
        self.verticalLayout_6.addWidget(self.checkBox_36)
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self.label_14 = QtGui.QLabel(self.verticalLayoutWidget_6)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_38.addWidget(self.label_14)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem2)
        self.lineEdit_4 = QtGui.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout_38.addWidget(self.lineEdit_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_38)
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.verticalLayoutWidget_7 = QtGui.QWidget(self.tab_7)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(0, 10, 281, 71))
        self.verticalLayoutWidget_7.setObjectName(_fromUtf8("verticalLayoutWidget_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.checkBox_37 = QtGui.QCheckBox(self.verticalLayoutWidget_7)
        self.checkBox_37.setEnabled(False)
        self.checkBox_37.setObjectName(_fromUtf8("checkBox_37"))
        self.verticalLayout_7.addWidget(self.checkBox_37)
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName(_fromUtf8("horizontalLayout_39"))
        self.label_25 = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.label_25.setEnabled(False)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_39.addWidget(self.label_25)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem3)
        self.lineEdit_5 = QtGui.QLineEdit(self.verticalLayoutWidget_7)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.horizontalLayout_39.addWidget(self.lineEdit_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_39)
        self.tabWidget_2.addTab(self.tab_7, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget_2)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_3.addWidget(self.label_11)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.checkBox_33 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_33.setEnabled(True)
        self.checkBox_33.setCheckable(True)
        self.checkBox_33.setChecked(True)
        self.checkBox_33.setObjectName(_fromUtf8("checkBox_33"))
        self.horizontalLayout_30.addWidget(self.checkBox_33)
        self.checkBox_34 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_34.setObjectName(_fromUtf8("checkBox_34"))
        self.horizontalLayout_30.addWidget(self.checkBox_34)
        self.verticalLayout_3.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.checkBox_31 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_31.setObjectName(_fromUtf8("checkBox_31"))
        self.horizontalLayout_29.addWidget(self.checkBox_31)
        self.checkBox_32 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_32.setObjectName(_fromUtf8("checkBox_32"))
        self.horizontalLayout_29.addWidget(self.checkBox_32)
        self.verticalLayout_3.addLayout(self.horizontalLayout_29)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 3, 2, 1, 1)
        self.tabWidget.addTab(self.tab_fid, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.Multiecho.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit_fdfpath, self.pushButton_changefdf)
        Dialog.setTabOrder(self.pushButton_changefdf, self.lineEdit_dicompath)
        Dialog.setTabOrder(self.lineEdit_dicompath, self.pushButton_changedicom)
        Dialog.setTabOrder(self.pushButton_changedicom, self.lineEdit_darisid)
        Dialog.setTabOrder(self.lineEdit_darisid, self.buttonBox)
        Dialog.setTabOrder(self.buttonBox, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.lineEdit_fidpath)
        Dialog.setTabOrder(self.lineEdit_fidpath, self.pushButton_changefid)
        Dialog.setTabOrder(self.pushButton_changefid, self.lineEdit_dicompath2)
        Dialog.setTabOrder(self.lineEdit_dicompath2, self.pushButton_changedicom2)
        Dialog.setTabOrder(self.pushButton_changedicom2, self.lineEdit_darisid2)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "MBI\'s FDF/FID DICOM converter", None))
        self.label_4.setText(_translate("Dialog", "Options", None))
        self.pushButton_changefdf.setToolTip(_translate("Dialog", "Change the FDF input directory", None))
        self.pushButton_changefdf.setText(_translate("Dialog", "Change Dir", None))
        self.label.setText(_translate("Dialog", "FDF folder", None))
        self.label_2.setText(_translate("Dialog", "Dicom folder", None))
        self.label_3.setText(_translate("Dialog", "DaRIS ID", None))
        self.pushButton_changedicom.setToolTip(_translate("Dialog", "Change the output DICOM directory.  Only do this if the automatic folder name is already taken.", None))
        self.pushButton_changedicom.setText(_translate("Dialog", "Change Dir", None))
        self.lineEdit_darisid.setToolTip(_translate("Dialog", "DaRIS ID string should automatically update with new FDF folder", None))
        self.checkBox_debugging.setToolTip(_translate("Dialog", "Display more verbose debugging", None))
        self.checkBox_debugging.setText(_translate("Dialog", "Show debugging", None))
        self.checkBox_nodcmulti.setToolTip(_translate("Dialog", "Do not convert 2D slices to enhance DICOM format", None))
        self.checkBox_nodcmulti.setText(_translate("Dialog", "Keep 2D DICOM slices", None))
        self.Multiecho.setTabText(self.Multiecho.indexOf(self.tab_generic), _translate("Dialog", "Generic", None))
        self.radioButton_bmatrixdiff.setText(_translate("Dialog", "Bmatrix", None))
        self.radioButton_directionaldiff.setText(_translate("Dialog", "Directional", None))
        self.label_10.setText(_translate("Dialog", "TextLabel", None))
        self.checkBox_diffusion1.setText(_translate("Dialog", "Diffusion", None))
        self.Multiecho.setTabText(self.Multiecho.indexOf(self.tab_diffusion), _translate("Dialog", "Diffusion", None))
        self.label_15.setText(_translate("Dialog", "TextLabel", None))
        self.checkBox_7.setText(_translate("Dialog", "Multi-echo", None))
        self.Multiecho.setTabText(self.Multiecho.indexOf(self.tab_multiecho), _translate("Dialog", "Multi echo", None))
        self.pushButton_convert.setToolTip(_translate("Dialog", "Convert FDF folder to DICOM", None))
        self.pushButton_convert.setText(_translate("Dialog", "Convert", None))
        self.pushButton_check.setText(_translate("Dialog", "Check", None))
        self.pushButton_view.setText(_translate("Dialog", "View", None))
        self.pushButton_send2daris.setToolTip(_translate("Dialog", "Send Dicom folder to DaRIS ", None))
        self.pushButton_send2daris.setText(_translate("Dialog", "Send to DaRIS", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_fdf), _translate("Dialog", "FDF converter", None))
        self.label_8.setText(_translate("Dialog", "DaRIS ID", None))
        self.label_5.setText(_translate("Dialog", "Options", None))
        self.pushButton_changefid.setToolTip(_translate("Dialog", "Change the input FID directory", None))
        self.pushButton_changefid.setText(_translate("Dialog", "Change Dir", None))
        self.label_6.setText(_translate("Dialog", "FID folder", None))
        self.label_7.setText(_translate("Dialog", "Dicom folder", None))
        self.pushButton_changedicom2.setToolTip(_translate("Dialog", "Change the output DICOM directory.", None))
        self.pushButton_changedicom2.setText(_translate("Dialog", "Change Dir", None))
        self.lineEdit_darisid2.setToolTip(_translate("Dialog", "DaRIS ID generated from header information in FID procpar.  Do not edit unless you know what you are doing!", None))
        self.pushButton_convertfid.setToolTip(_translate("Dialog", "Run the fid2dcm script", None))
        self.pushButton_convertfid.setText(_translate("Dialog", "Convert", None))
        self.pushButton_check2.setToolTip(_translate("Dialog", "Check the unfiltered reconstruction DICM", None))
        self.pushButton_check2.setText(_translate("Dialog", "Check", None))
        self.pushButton_view2.setToolTip(_translate("Dialog", "View the filtered and unfiltered images", None))
        self.pushButton_view2.setText(_translate("Dialog", "View", None))
        self.pushButton_send2daris2.setToolTip(_translate("Dialog", "Send DICOMs to Daris", None))
        self.pushButton_send2daris2.setText(_translate("Dialog", "Send to DaRIS", None))
        self.label_9.setText(_translate("Dialog", "Filters", None))
        self.tabWidget_2.setToolTip(_translate("Dialog", "Multidimensional median, Gaussian or Wiener  filters.", None))
        self.label_19.setToolTip(_translate("Dialog", "order : {0, 1, 2, 3} or sequence from same set, optional\n"
"\n"
"    The order of the filter along each axis is given as a sequence of integers, or as a single number. An order of 0 corresponds to convolution with a Gaussian kernel. An order of 1, 2, or 3 corresponds to convolution with the first, second or third derivatives of a Gaussian. Higher order derivatives are not implemented\n"
"", None))
        self.label_19.setText(_translate("Dialog", "Order", None))
        self.lineEdit_window_4.setToolTip(_translate("Dialog", "order : {0, 1, 2, 3} or sequence from same set, optional\n"
"\n"
"    The order of the filter along each axis is given as a sequence of integers, or as a single number. An order of 0 corresponds to convolution with a Gaussian kernel. An order of 1, 2, or 3 corresponds to convolution with the first, second or third derivatives of a Gaussian. Higher order derivatives are not implemented\n"
"", None))
        self.lineEdit_window_4.setText(_translate("Dialog", "0", None))
        self.label_20.setToolTip(_translate("Dialog", "scalar or sequence of scalars\n"
"\n"
"    Standard deviation for Gaussian kernel. The standard deviations of the Gaussian filter are given for each axis as a sequence, or as a single number, in which case it is equal for all axes.", None))
        self.label_20.setText(_translate("Dialog", "Sigma", None))
        self.lineEdit_sigma_4.setToolTip(_translate("Dialog", "scalar or sequence of scalars\n"
"\n"
"    Standard deviation for Gaussian kernel. The standard deviations of the Gaussian filter are given for each axis as a sequence, or as a single number, in which case it is equal for all axes.", None))
        self.lineEdit_sigma_4.setText(_translate("Dialog", "0.707", None))
        self.checkBox_24.setToolTip(_translate("Dialog", " scipy.ndimage.filters.gaussian_filter(input, sigma, order=0, output=None, mode=\'reflect\', cval=0.0, truncate=4.0)[source]\n"
"\n"
"    Multidimensional Gaussian filter.", None))
        self.checkBox_24.setText(_translate("Dialog", "Use Gaussian Filter", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("Dialog", "Gaussian", None))
        self.checkBox_36.setToolTip(_translate("Dialog", "scipy.ndimage.filters.median_filter¶\n"
"\n"
"scipy.ndimage.filters.median_filter(input, size=None, footprint=None, output=None, mode=\'reflect\', cval=0.0, origin=0)[source]\n"
"\n"
"    Calculates a multidimensional median filter.", None))
        self.checkBox_36.setText(_translate("Dialog", "Use Median Filter", None))
        self.label_14.setToolTip(_translate("Dialog", "     \n"
"\n"
"size : scalar or tuple, optional\n"
"\n"
"    See footprint, below\n"
"\n"
"footprint : array, optional\n"
"\n"
"    Either size or footprint must be defined. size gives the shape that is taken from the input array, at every element position,\n"
" to define the input to the filter function. footprint is a boolean array that specifies (implicitly) a shape,\n"
" but also which of the elements within this shape will get passed to the filter function. Thus size=(n,m) is equivalent to footprint=np.ones((n,m)).\n"
" We adjust size to the number of dimensions of the input array, so that, if the input array is shape (10,10,10),\n"
" and size is 2, then the actual size used is (2,2,2).\n"
"", None))
        self.label_14.setText(_translate("Dialog", "Window Size(s)", None))
        self.lineEdit_4.setToolTip(_translate("Dialog", "     \n"
"\n"
"size : scalar or tuple, optional\n"
"\n"
"    See footprint, below\n"
"\n"
"footprint : array, optional\n"
"\n"
"    Either size or footprint must be defined. size gives the shape that is taken from the input array, at every element position,\n"
" to define the input to the filter function. footprint is a boolean array that specifies (implicitly) a shape,\n"
" but also which of the elements within this shape will get passed to the filter function. Thus size=(n,m) is equivalent to footprint=np.ones((n,m)).\n"
" We adjust size to the number of dimensions of the input array, so that, if the input array is shape (10,10,10),\n"
" and size is 2, then the actual size used is (2,2,2).\n"
"", None))
        self.lineEdit_4.setText(_translate("Dialog", "5", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("Dialog", "Median", None))
        self.checkBox_37.setToolTip(_translate("Dialog", "NOT ENABLED - Speak to MBI Imaging Team\n"
"\n"
"scipy.signal.wiener(im, mysize=None, noise=None)\n"
"\n"
"    Perform a Wiener filter on an N-dimensional array.\n"
"\n"
"    Apply a Wiener filter to the N-dimensional array im.", None))
        self.checkBox_37.setText(_translate("Dialog", "Use Wiener Filter", None))
        self.label_25.setToolTip(_translate("Dialog", "mysize : int or arraylike, optional\n"
"\n"
"    A scalar or an N-length list giving the size of the Wiener filter window in each dimension. Elements of mysize should be odd. If mysize is a scalar, then this scalar is used as the size in each dimension.\n"
"", None))
        self.label_25.setText(_translate("Dialog", " Window Size(s)", None))
        self.lineEdit_5.setToolTip(_translate("Dialog", "mysize : int or arraylike, optional\n"
"\n"
"    A scalar or an N-length list giving the size of the Wiener filter window in each dimension. Elements of mysize should be odd. If mysize is a scalar, then this scalar is used as the size in each dimension.\n"
"", None))
        self.lineEdit_5.setText(_translate("Dialog", "5", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("Dialog", "Wiener", None))
        self.label_11.setText(_translate("Dialog", "Outputs of Filter", None))
        self.checkBox_33.setText(_translate("Dialog", "Save Magnitude", None))
        self.checkBox_34.setText(_translate("Dialog", "Save Phase", None))
        self.checkBox_31.setText(_translate("Dialog", "Save REAL and IMAG", None))
        self.checkBox_32.setText(_translate("Dialog", "Save K space data", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_fid), _translate("Dialog", "FID converter", None))

