#! /bin/gawk -f
#
# Display Agilent Parameter file 'procpar' alpbetically sorted 
#
#
# Copyright (C) 2014 Michael Eager  (michael.eager@monash.edu)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
BEGIN{
#	metadata=[]
	str=""
	idx=0
} 
{
	if (match($1,"^[a-z]")){ 
	  metadata[idx] = str;
	  idx=idx+1 
	  str=$0
	} else {
	  str=str " " $0 
	}
}
END {
    meatdata[idx]=str
    n = asort(metadata)
    for (i = 1; i <= n; i++)
    	print metadata[i]
}
